# User Parameters
Model: "mistral-nemo" # Specify the model name
batch-size: 5 # How many titles to compare at once.
theme: "catppuccin-Mocha"
os: "unix" # "unix" or "windows"
path: "Users/cjones/Desktop" # Path to the data folder
